### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by fahad-ra** [engrsaifkhan/WeatherApp#1]
It's basically not working as an weather reporting app.

**Comment by engrsaifkhan** [comment]
It is basically showing the different states of weather on different temperatures and alert some message for user on the basis of user input temperature. Currently it is not using any Weather API. Further development is continue to launch it as "Weather Reporting App"

**Comment by fahad-ra** [comment]
It would be beneficial if you rename this app according to its functionality.

Or we could start implementing weather Api as well.

**Comment by engrsaifkhan** [comment]
Your suggestion is valuable. I am re thinking on it. Need some time
